version: '3.8'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-service
    networks:
      - bank_network
    ports:
      - "4000:4000"

networks:
  bank_network:
    external: true
